VerifiedInc/Kredita-Demo-Web

.circleci/config.yml, Dockerfile, package-lock.json, package.json
Updated to use latest version of node, npm, and the CI orb. Updated CI config so that Github branch status checks only have to look at lint-and-test.
- Dockerfile to better support image caching and other improvements
- CI config updated to use latest orb with image caching and workflow setup
- deployed using test ci branch
=> [Versions] updated: orb, node, npm. Also Dockerfile updated. 

package-lock.json, package.json
[Ticket](https://trello.com/c/NdfGiGJZ/5582-review-merge-dependabot-prs)
Updates vulnerable dependencies reported by dependabot
=> fix: update vulnerable dependencies

.circleci/config.yml, .env.example, .gitignore, Dockerfile, app/config.client.ts, app/config.ts, app/entry.client.tsx, app/entry.server.tsx, app/root.tsx, app/sentry.client.ts, app/sentry.server.ts, package-lock.json, package.json, server.js
[Ticket](https://trello.com/c/CkVgjLnw/5865-add-sentry-for-hooli-and-kredita-projects)
This PR adds Sentry configuration.
- Added Sentry
- Bumped Remix to ^1.18.0 to have build with sourcemap
- x ] I have commented my code, particularly in hard-to-understand areas _to a borderline excessive amount_
=> chore: add sentry config

.circleci/config.yml
[CI] updated to push the release image to production
=> [CI] updated to push the release image to production

app/coreAPI.server.ts
=> refactor: remove credential requests from one click endpoint

app/routes/register.tsx
[Ticket](https://trello.com/c/KHSrzmYK/6517-use-first-name-on-kredita-demo)
The session now contains only the first name.
- updated the loader function
=> refactor: add first name only to session

server.js
[CSP] docs url and localhost added to frame-ancestors
- [CSP] docs url added to frame-ancestors
- localhost
- localhost docs project
=> [CSP] docs url added to frame-ancestors

Dockerfile, package.json
chore: upgrade node version to 20.10.0-alpine
=> chore: upgrade node version to 20.10.0-alpine

app/features/register/components/OneClickForm.tsx, app/routes/register.tsx
=> fix: submit form on phone input change and valid

app/coreAPI.server.ts
=> chore: change to signup

app/features/register/components/OneClickForm.tsx, app/routes/index.tsx, app/routes/register.tsx, app/routes/verified.tsx, app/styles/theme.ts
[Ticket](https://trello.com/c/lSTgtcCE/6547-change-logout-button-to-sign-out-and-copy-it-to-also-be-on-the-kredita-success-page-under-the-go-to-home-button)
[Ticket](https://trello.com/c/lSTgtcCE/6547-change-logout-button-to-sign-out-and-copy-it-to-also-be-on-the-kredita-success-page-under-the-go-to-home-button)
Rename term logout to sign out. Also adds sign out button on success page.
- updated verified page
- updated dashboard page
Tested locally
| Success page | Dashboard page |
|--------|--------|
| ![image](https://github.com/VerifiedInc/Kredita-Demo-Web/assets/13892132/8be05272-afe5-4c4c-aa26-e40e7e75ac32) | ![image](https://github.com/VerifiedInc/Kredita-Demo-Web/assets/13892132/5db4ef4e-5aef-481e-802b-268bb0620e4b) |
=> add reenter signout

app/features/register/components/OneClickForm.tsx, app/routes/index.tsx, app/routes/verified.tsx, app/session.server.ts
=> fix: keep session of redirect param

app/routes/register.tsx
[Ticket]()
Add shared credentials uuid param to verified page.
- updated loader
=> chore: add search params to verified page

app/features/register/components/OneClickForm.tsx
[Ticket](https://trello.com/c/zT4yPekt/6581-update-kredita-demo-legal-text-to-say-by-using-this-kredita-demo-you-agree-to-verified-incs-terms-of-use-and-acknowledge-our-pri)
Update the legal text.
- updated legal text
=> chore: update legal text

.env.example, README.md, app/config.ts, app/coreAPI.server.ts, app/root.tsx, app/routes/register.tsx, app/session.server.ts
[Ticket]()
Fetches the API key of a brand when it is set or existing to allow the users to go through an entire journey with the correct brand display on the web wallet.
- updated brand session
- added get api key endpoint
=> chore: get brand api key

app/components/PhoneInput.tsx
[Ticket]()
Fix the input mode for phone input to display a numerical keyboard.
- updated phone input component
=> fix: add input mode numeric in inputProps

.circleci/config.yml
CI updated to deploy the white-labelled version. This is considered a `hotfix` in order to get the automated sandbox deployment working upon release creation for the white-labelled flavor.
- [CI] updated to deploy the white labelled version.
- via test-circleci branch
=> [CI] updated to deploy the white labelled version.

app/features/register/components/OneClickForm.tsx, app/hooks/useBrand.ts, app/root.tsx, app/routes/register.tsx
[Ticket]()
Remove cookie usage and use remix loader data instead to consume the brand and API key to the page session.
=> chore: remove cookie usage

app/coreAPI.server.ts, app/routes/register.tsx, package-lock.json, package.json
[Ticket](https://trello.com/c/N7Atwr0V/6611-1-click-update-kredita-demo-to-use-get-1-click-uuid-and-retrieve-full-name-value)
Added the 1-click route to get the shared credentials and populate on user session.
- updated register loader
- added 1-click service call
- updated core-types
=> 1 click credentials

app/coreAPI.server.ts
[Ticket]()
Remove the default options on 1-click body.
- updated core service call
=> refactor: remove default options

app/routes/verified.tsx
[Ticket]()
Not cloning the request object causes an error `Error: cannot clone body after it is used`; this PR fixes it.
- updated action
=> fix: clone request

app/routes/verified.tsx
[Ticket]()
Fix brand name display on verified page and correct spacing between logo and heading.
- updated layout
- updated verified page
=> fix: add brand name and space fix

app/coreAPI.server.ts, app/utils/getBrandSet.ts
[Ticket]()
Add more logs to observe the request to get api keys.
=> chore: add logs

app/routes/register.tsx
[Ticket]()
Extract full name from string or record.
=> fix: access full name conditionally

.env.example, app/components/OTPInput.tsx, app/components/PhoneInput.tsx, app/config.client.ts, app/config.ts, app/coreAPI.server.ts, app/features/personalInformation/hooks/usePersonalInformationFields.ts, app/features/personalInformation/types.ts, app/features/register/components/OneClickForm.tsx, app/features/register/components/OneClickFormNonHosted.tsx, app/features/register/components/OneClickHeader.tsx, app/features/register/components/OneClickLegalText.tsx, app/hooks/useField.ts, app/hooks/useIsOneClickNonHosted.ts, app/root.tsx, app/routes/personal-information.tsx, app/routes/register.tsx, app/utils/getBrand.ts, app/validations/birthDate.schema.ts, app/validations/birthday.schema.ts, app/validations/country.schema.ts, app/validations/email.schema.ts, app/validations/field.schema.ts, app/validations/oneClickNonHosted.schema.ts, app/validations/ssn.schema.ts, app/validations/state.schema.ts
[Ticket](https://trello.com/c/6tx2rYnl/6621-build-new-version-of-1-click-signup-demo-that-shows-the-non-hosted-version)
Added non-hosted flows for 1-click and added a personal information page where fills in the 1-click result to it and redirect to client url.
Also new env var was added `ONE_CLICK_NON_HOSTED_ENABLED`
- added new page
- handled 1-click non-hosted
- added new validations
- added new components
=> feat: 1 click non hosted
